// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlHpu2Ap8vK4YbFWErjyELLrAEVf_NH3U',
    appId: '1:1056185451111:web:8546297cd09a01becdcac2',
    messagingSenderId: '1056185451111',
    projectId: 'bustrack-369516',
    authDomain: 'bustrack-369516.firebaseapp.com',
    storageBucket: 'bustrack-369516.appspot.com',
    measurementId: 'G-5MPWY1L1LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6phNswAY_lUDzjjxVSgRddO9pFyr7lA',
    appId: '1:1056185451111:android:70ababa8fd4e16a7cdcac2',
    messagingSenderId: '1056185451111',
    projectId: 'bustrack-369516',
    storageBucket: 'bustrack-369516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY3WsdoxDqIpMAwwDsAY3JTMZ9a7lPwMw',
    appId: '1:1056185451111:ios:47357631b0770a51cdcac2',
    messagingSenderId: '1056185451111',
    projectId: 'bustrack-369516',
    storageBucket: 'bustrack-369516.appspot.com',
    iosClientId: '1056185451111-q9dcg5cvg0nqq5pl4e48dtomld6eks8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY3WsdoxDqIpMAwwDsAY3JTMZ9a7lPwMw',
    appId: '1:1056185451111:ios:47357631b0770a51cdcac2',
    messagingSenderId: '1056185451111',
    projectId: 'bustrack-369516',
    storageBucket: 'bustrack-369516.appspot.com',
    iosClientId: '1056185451111-q9dcg5cvg0nqq5pl4e48dtomld6eks8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerClient',
  );
}
